### PR TITLE
Fix #3 - Avoid invoking plantuml_connection for invalid server

### LINKED ISSUE #3: Request: Option to skip trying the server
I want to always use the `.jar`. We have some paranoia here around uploading our diagrams source, which is proprietary information, to some service. I could run a local server, but that means an extra step to run it that I could just avoid by pointing to the `.jar` and use that all the time. I think the plugin ends up being a tiny bit slow because it tries the server before realizing it won't work then finally uses the `.jar`. An option to just skip trying the server entirely would be ideal to save time and always-failing network calls.

Thanks!

### PR DESCRIPTION
**Pull request by xenofanes9**
Avoid invoking plantuml_connection and generating content to send to server if 'plantuml_server' set to invalid server
* For cases where specified server won't work (i.e. "plantuml_server": ""), avoids generating server request.

### CODE REVIEW

**Comment by xenofanes9** [comment]
Change does a simple verification of the URL scheme (for "http" or "https") of the server URL before invoking the plantuml_connection.

**Comment by evandrocoan** [comment]
Did you implemented it because it was slow before?

**Comment by xenofanes9** [comment]
I believe I noticed a small speed-up, but didn't time it.  Was also cluttering ST debug logs like crazy, as the whole zipped content URL was being dumped each time.

**Comment by evandrocoan** [comment]
I see. Thanks!

**Pull request merged**
